# Generated by Django 4.2.5 on 2023-10-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('price', models.CharField(max_length=8, verbose_name='price')),
                ('note', models.CharField(max_length=100, null=True, verbose_name='note')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('metro_station', models.CharField(max_length=50, null=True, verbose_name='metro')),
                ('schedule', models.CharField(max_length=50, verbose_name='schedule')),
                ('number', models.CharField(max_length=50, verbose_name='number')),
                ('telegram', models.CharField(max_length=200, null=True, verbose_name='telegram')),
                ('inst', models.CharField(max_length=200, null=True, verbose_name='inst')),
                ('vk', models.CharField(max_length=200, null=True, verbose_name='vk')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.city')),
            ],
        ),
    ]
