# Generated by Django 4.2.5 on 2023-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branchoffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15, verbose_name='city')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('schedule', models.CharField(max_length=50, verbose_name='schedule')),
                ('number', models.CharField(max_length=50, verbose_name='number')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('price', models.CharField(max_length=8, verbose_name='price')),
                ('note', models.CharField(max_length=100, null=True, verbose_name='note')),
            ],
        ),
    ]
